### ISSUE TITLE
Can't make it work with uxrvt.

### ISSUE THREAD

**Issue by Sifiros** [liuchengxu/space-vim-dark#20] opened 2018-07-26 18:16 UTC
Hi there,
This colorscheme looks awesome but i can't make it work with rxvt-unicode (urxvt) v9.22.
My $TERM returns rxvt-unicode-256color.
I have tested with lxterminal and it works well but i have no colors with URXVT and bottom bars icons are not display either.
![2018-07-26-20 20 59_1920x1080_scrot](https://user-images.githubusercontent.com/18138381/43280246-964f24e2-9110-11e8-9589-3c5e8602ba55.png)

I used the .Xresoucres from this repo btw. Do you have some hints ? Thanks

**Comment by liuchengxu** [comment] 2018-07-27 02:32
I personally never used uxrvt, @axvr may help here.

**Comment by axvr** [comment] 2018-07-27 06:39
@Sifiros, I think this issue may be caused by urxvt's lack of support for true colour (24bit) support. It may work if you use `set notermguicolors` in Vim.

(This is assuming that you are not using Tmux)

Also, if this is your first time using urxvt, checkout the [Arch Wiki page on urxvt](https://wiki.archlinux.org/index.php/Rxvt-unicode).

**Comment by Sifiros** [comment] 2018-07-27 08:28
@axvr 
Thanks for your answer, using `set notermguicolors`, colors appears, just not the good ones.
I still don't have bottom and top bars icons (I have them with lxterminal).
Using the .Xresources,  do you use `color space-vim-dark` in your vimrc or is it useless (i don't currently have it) ? Can this be influence by the `t_Co` property ?
For information I don't use Tmux.
Thanks for your time.

**Comment by axvr** [comment] 2018-07-27 08:40
Yes you will need `color space-vim-dark` to use the space-vim-dark colours in Vim. The .Xresources colours are for other terminal applications running in urxvt, to add some consistency, but they are not needed for Vim to use Space-vim-dark.

The problem with the missing icons is most likely because you are using PowerLine/AirLine or some derivative of it. So to get those icons you will need a "patched" font. I don't use PowerLine so I am unable to help you there. One patched font I know of is [FiraCode](https://github.com/tonsky/FiraCode). I think you can set fonts and "fallback" fonts in your .Xresources file, so if that icon is missing, it can be loaded from another font pack.

Your `t_Co` option should be correctly set by default, to check this run: `echo &t_Co` and Vim should return 256.

**Comment by Sifiros** [comment] 2018-07-27 08:49
`set notermguicolors` and `color space-vim-dark` fixed the colors.
I'll try with the hack font, hope that will work. I'll set FiraCode as fallback.
Thanks a lot for your help.
Consider it solved :)

**Comment by liuchengxu** [comment] 2018-07-27 08:57
Closing... then.

**Closed as completed by liuchengxu** 2018-07-27 08:57 UTC
